teksten={'labelperron':     {'en':'Platform: ', 'nl':'Perron: '},
         'noLocation':      {'en': 'Cannot find location, please try again' , 'nl':'Kan de locatie niet vinden, probeer opnieuw.'},
         'actueelTitelLoc': {'en':'Current departures', 'nl':'Actuele vertrektijden:'},
         'button1':         {'en':'I don\'t have\n an OV-chipcard', 'nl':'Ik heb geen \nOV-chipkaart'},
         'button2':         {'en': 'I want to go abroad', 'nl': 'Ik wil naar het \n buitenland'},
         'button3':         {'en': 'Travelinformation', 'nl': 'Reisinformatie'},
         'backbutton2':     {'en': 'Back to main menu', 'nl': 'Terug naar \n het hoofdmenu'},
         'button4':         {'en': 'Current location', 'nl': 'Huidige Locatie'},
         'button5':         {'en': 'Other location', 'nl': 'Andere locatie'},
         'button6':        {'en': 'Search', 'nl': 'Zoek'},
         'button7':        {'en': 'Next 8 stations', 'nl': 'Volgende 8 stations'},
         'button8':        {'en': 'Last 8 stations', 'nl': 'Vorige 8 stations'},
         'button9':        {'en': 'Search again', 'nl': 'Zoek opnieuw'},
         'button10':        {'en': 'Next 8 stations', 'nl': 'Volgende 8 stations'},
         'button11':        {'en': 'Last 8 stations', 'nl': 'Laatste 8 stations'},
         'background':      {'en': "WelcometoNS.png", 'nl': "images\\welkombijns.png"},
         'toetsenbord':     {'en': 'Space','nl': 'Spatie'}}
#         'switch:        {'en': '', 'nl': ''},